In [1]:
import numpy as np
from scipy.stats import zscore

data = np.array([[10, 20], [30, 40], [50, 60]])
z = zscore(data)
print(z)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [2]:
import pandas as pd
from scipy.stats import zscore

df = pd.DataFrame({
    'height': [160, 170, 180],
    'weight': [55, 65, 75]
})

df_z = df.apply(zscore)
print(df_z)

     height    weight
0 -1.224745 -1.224745
1  0.000000  0.000000
2  1.224745  1.224745


In [5]:
z = zscore(df['height'])
df['height_z'] = z
print(df)
outliers = df[np.abs(df['height_z']) > 2]
outliers

   height  weight  height_z
0     160      55 -1.224745
1     170      65  0.000000
2     180      75  1.224745


Empty DataFrame
Columns: [height, weight, height_z]
Index: []

In [2]:
from sklearn.linear_model import LogisticRegression
import inspect
inspect.signature(LogisticRegression)

<Signature (penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='deprecated', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)>

在一片广袤的沙滩上，小 Q 在捡贝壳，他对每一个贝壳都有一个“喜爱度”。目前已知沙滩上有 n 个贝壳，他的口袋可以装下m 个贝壳，因为他太喜欢贝壳了，所以他一定会把口袋装满。小 Q 的开心程度与口袋里贝壳的“喜爱度”有关，即口袋里所有贝壳的“喜爱度”作与运算之后的结果，就是小 Q 的开心程度。请你帮忙计算他的开心程度最大是多少。

In [ ]:
def max_happiness(arr, m):
    # m = input()
    # n = input()
    # arr = list(map(int,input().split(' ')))
    candidates = arr[:]
    ans = 0
    for bit in reversed(range(32)):  # 从高位到低位
        mask = 1 << bit
        # 筛选保留当前位为 1 且和已有 ans 的位一致的数
        filtered = [x for x in candidates if (x & mask) and ((x & ans) == ans)]
        if len(filtered) >= m:
            ans |= mask
            candidates = filtered
    # 从 candidates 中任选 m 个计算最终 & 值
    from itertools import combinations
    max_and = 0
    for comb in combinations(candidates, m):
        res = comb[0]
        for num in comb[1:]:
            res &= num
        max_and = max(max_and, res)
    return max_and


n = 5
m = 3
likes = [5, 7, 15, 3, 9]
print(max_happiness(likes, m))

5


In [ ]:
from itertools import combinations

n = int(input())
m = int(input())
likes = input()
arr = [int(i) for i in likes if i != ' ']
candidates = arr[:]
ans = 0
for bit in reversed(range(32)):  # 从高位到低位
    mask = 1 << bit
    # 筛选保留当前位为 1 且和已有 ans 的位一致的数
    filtered = [x for x in candidates if (x & mask) and ((x & ans) == ans)]
    if len(filtered) >= m:
        ans |= mask
        candidates = filtered
# 从 candidates 中任选 m 个计算最终 & 值

max_and = 0
for comb in combinations(candidates, m):
    res = comb[0]
    for num in comb[1:]:
        res &= num
    max_and = max(max_and, res)
print(max_and)

2 10 7 3 71

秋天是收获的季节。农民小 Q 有一片 $n × m$ 的麦田，麦田每一块地可以收获 $a_{ij} (1<i<n, 1<j<m)$吨重的小麦 。这天小 Q 家里来了一位收麦员，收麦员最多可以接收 M 吨小麦，小 Q 要将小麦卖给收麦员赚钱！小 Q 是一个完美主义者，他只会将麦田里一块完整的矩形区域收割售卖。与收麦员交易需要一定的手续费，但是收麦员对于小 Q 的收割要求很感兴趣，他提出如果小 Q 可以计算出他的麦田有多少种收割方式，那么将免除手续费。请你帮小 Q 省下这笔手续费。

In [ ]:
def count_valid_subrectangles(a, M):
    n = len(a)
    m = len(a[0])
    
    # 构建二维前缀和，前缀和数组从1开始，方便边界处理
    prefix = [[0]*(m+1) for _ in range(n+1)]
    
    for i in range(n):
        for j in range(m):
            prefix[i+1][j+1] = (
                prefix[i][j+1] +
                prefix[i+1][j] -
                prefix[i][j] +
                a[i][j]
            )
    
    def get_sum(r1, c1, r2, c2):
        # 输入都是1-based坐标，返回子矩形的和
        return (prefix[r2][c2]
                - prefix[r1-1][c2]
                - prefix[r2][c1-1]
                + prefix[r1-1][c1-1])
    
    count = 0
    for r1 in range(1, n+1):
        for r2 in range(r1, n+1):
            for c1 in range(1, m+1):
                for c2 in range(c1, m+1):
                    if get_sum(r1, c1, r2, c2) <= M:
                        count += 1
    return count


a = [
    [1, 2, 3],
    [4, 5, 6]
]
M = 8
print(count_valid_subrectangles(a, M))  

11


In [1]:
sss = '1 1 2'
[int(x) for x in sss.split(' ')]

[1, 1, 2]

In [3]:
from IPython.display import display, Math
display(Math(r'\mathrm{R{-}X} + \mathrm{NaOR'} \rightarrow \mathrm{R{-}O{-}R'} + \mathrm{NaX}'))

SyntaxError: closing parenthesis '}' does not match opening parenthesis '(' (1924173774.py, line 2)

In [5]:
import re
text = "hermione+rege+xone@+hogwarts.com"
m = re.search(r'(.*(?=@))(?=\+)', text)
if m:
    print("✅ 匹配成功:", m.group(1))
else:
    print("❌ 匹配失败")

❌ 匹配失败


In [40]:
import pandas as pd

data = {'col_1': [3, 2, 4, 1, 0], 'col_2': ['a', 'b', 'c', 'd', 'c']}
df = pd.DataFrame.from_dict(data)

print(df)

   col_1 col_2
0      3     a
1      2     b
2      4     c
3      1     d
4      0     c


In [50]:
type(df['col_2'].value_counts())

pandas.core.series.Series

In [48]:
'helloworld'.find('ggg')

-1

In [45]:
x= df['col_1'] - df['col_1'].mean()
x

0    1.0
1    0.0
2    2.0
3   -1.0
4   -2.0
Name: col_1, dtype: float64

In [10]:
import pandas as pd

fruits = pd.DataFrame.from_dict({'Apples':[30], 'Bananas':[21]})
fruits

Apples  Bananas
0      30       21

In [2]:
import pandas as pd

# 创建两个Series对象
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([4, 5, 6], index=['b', 'c', 'd'])
print(s1, s2)

s3 = s1 + s2
s3

a    1
b    2
c    3
dtype: int64 b    4
c    5
d    6
dtype: int64


a    NaN
b    6.0
c    8.0
d    NaN
dtype: float64

In [ ]:
# 列合并，形成DataFrame
result = pd.concat([s1, s2], axis=1, ignore_index=True)
result

TypeError: concat() got an unexpected keyword argument 'columns'

In [1]:
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

oe = OrdinalEncoder()
X = np.array([['low'], ['medium'], ['high'], ['medium']])
X_encoded = oe.fit_transform(X)
print(X_encoded)

[[1.]
 [2.]
 [0.]
 [2.]]


In [2]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = ['cat', 'dog', 'dog', 'fish']
y_encoded = le.fit_transform(y)
print(y_encoded)  # 输出: [0 1 1 2]
print(le.inverse_transform(y_encoded))  # 输出: ['cat' 'dog' 'dog' 'fish']


[0 1 1 2]
['cat' 'dog' 'dog' 'fish']


In [3]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 假设你的数据如下：
df = pd.DataFrame({
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'value': [100, 200, 300, 400, 500]
})

# 创建编码器
le = LabelEncoder()

# 对 'color' 列进行编码
df['color_encoded'] = le.fit_transform(df['color'])

print(df)

   color  value  color_encoded
0    red    100              2
1  green    200              1
2   blue    300              0
3  green    400              1
4    red    500              2
